lib/cornelia_kelinske_web/router.ex
defmodule CorneliaKelinskeWeb.Router do
  use CorneliaKelinskeWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_flash
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", CorneliaKelinskeWeb do
    pipe_through :browser

    get "/", EnController, :index
    post "/contact", ContactController, :create
  end

  scope "/en", CorneliaKelinskeWeb do
    pipe_through :browser

    get "/", EnController, :index
    get "/overview", EnController, :overview
    get "/aboutme", EnController, :aboutme
    get "/feedback", EnController, :feedback
    get "/interpretation", EnController, :interpretation
    get "/translation", EnController, :translation
    get "/licenses", EnController, :licenses
    get "/contact", ContactController, :new
  end

  scope "/de", CorneliaKelinskeWeb do
    pipe_through :browser

    get "/", DeController, :index
    get "/ubermich", DeController, :ubermich
    get "/allgemeines", DeController, :allgemeines
    get "/feedback", DeController, :feedback
    get "/ubersetzen", DeController, :ubersetzen
    get "/dolmetschen", DeController, :dolmetschen
    get "/linzenzen", DeController, :linzenzen
    get "/kontakt", ContactController, :neu
  end

  if Application.get_env(:cornelia_kelinske, :env) === :dev do
    forward("/sent_email", Bamboo.SentEmailViewerPlug)
  end
end

lib/cornelia_kelinske_web/controllers/de_controller.ex
defmodule CorneliaKelinskeWeb.DeController do
  use CorneliaKelinskeWeb, :controller
  alias CorneliaKelinske.Feedback

  @spec index(Plug.Conn.t(), map) :: Plug.Conn.t()
  def index(conn, _params) do
    render(conn, "index.html", lang: :de, title: "Willkommen", feedback: Feedback.index_german())
  end

  @spec ubermich(Plug.Conn.t(), map) :: Plug.Conn.t()
  def ubermich(conn, _params), do: render(conn, "ubermich.html", lang: :de, title: "Über mich")

  @spec allgemeines(Plug.Conn.t(), map) :: Plug.Conn.t()
  def allgemeines(conn, _params),
    do: render(conn, "allgemeines.html", lang: :de, title: "Allgemeines")

  @spec feedback(Plug.Conn.t(), map) :: Plug.Conn.t()
  def feedback(conn, _params) do
    render(conn, "feedback.html", lang: :de, title: "Feedback", feedback: Feedback.german())
  end

  @spec ubersetzen(Plug.Conn.t(), map) :: Plug.Conn.t()
  def ubersetzen(conn, _params),
    do: render(conn, "ubersetzen.html", lang: :de, title: "Übersetzen")

  @spec dolmetschen(Plug.Conn.t(), map) :: Plug.Conn.t()
  def dolmetschen(conn, _params),
    do: render(conn, "dolmetschen.html", lang: :de, title: "Dolmetschen")

  @spec linzenzen(Plug.Conn.t(), map) :: Plug.Conn.t()
  def linzenzen(conn, _params), do: render(conn, "linzenzen.html", lang: :de, title: "Linzenzen")
end

lib/cornelia_kelinske_web/views/de_view.ex
defmodule CorneliaKelinskeWeb.DeView do
  use CorneliaKelinskeWeb, :view
end

lib/cornelia_kelinske_web/views/layout_view.ex
defmodule CorneliaKelinskeWeb.LayoutView do
  use CorneliaKelinskeWeb, :view
end

lib/cornelia_kelinske_web/templates/layout/de/_footer.html.eex
<footer class="footer container-fluid bg-brown4 d-flex justify-content-between border-top border-orange2">
    <%= link to: Routes.de_path(@conn, :linzenzen), class: "text-footer" do %>
        <%= icon("help-circle") %><span class="d-none d-sm-inline-block pl-1"> Linzenzen</span>
    <% end %>
    <%= link to: Routes.contact_path(@conn, :neu), class: "text-footer" do %>
        <%= icon("mail") %><span class="d-none d-sm-inline-block pl-1"> Kontakt Cornelia</span>
    <% end %>
    <%= link to: "https://www.alanvardy.com/", class: "text-footer", target: "_blank" do %>
        <%= icon("code") %><span class="d-none d-sm-inline-block pl-1"> Webmaster</span>
    <% end %>
</footer>

lib/cornelia_kelinske_web/templates/layout/de/_navbar.html.eex
<nav class="navbar navbar-expand-lg sticky-top navbar-dark bg-brown4 border-bottom border-orange2">
  <div class="container">
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup"
      aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav mr-auto">
        <%= link "Home", to: Routes.de_path(@conn, :index), class: "nav-item nav-link" %>
        <%= link "Über mich", to: Routes.de_path(@conn, :ubermich), class: "nav-item nav-link" %>
        <div class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            Leistungen
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <%= link "Allgemeines", to: Routes.de_path(@conn, :allgemeines), class: "dropdown-item" %>
            <%= link "Übersetzen", to: Routes.de_path(@conn, :ubersetzen), class: "dropdown-item" %>
            <%= link "Dolmetschen", to: Routes.de_path(@conn, :dolmetschen), class: "dropdown-item" %>
          </div>
        </div>
        <%= link "Feedback", to: Routes.de_path(@conn, :feedback), class: "nav-item nav-link" %>
        <%= link "Kontakt", to: Routes.contact_path(@conn, :neu), class: "nav-item nav-link" %>

      </div>
      <div class="navbar-nav">
        <%= link to: Routes.en_path(@conn, :index), class: "nav-item nav-link" do %>
          <%= img_tag "/images/canadian.svg", class: "flag d-inline border" %>
          <span class="d-inline">English</span>
        <% end %>
      </div>
    </div>
  </div>
</nav>